name: Julliet Automation - GTM - Develop

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  schedule:
    - cron: '0 13 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm install
          start: npm run cypress:run